services:
  api:
    build:
      context: ./vendergas_api
    container_name: api-vendergas
    ports:
      - "3000:3000"
    volumes:
      - ./vendergas_api:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./vendergas_api/.env
    command: npm run dev
